


lista_camion_mineria = [{'Origen': 'OLAVARRIA',
  'ID origen': 1,
  'Destino': 'OLAVARRIA',
  'ID destino': 1,
  'Carga': 39319,
  'Distancia': 0},
 {'Origen': 'CABA',
  'ID origen': 2,
  'Destino': 'OLAVARRIA',
  'ID destino': 1,
  'Carga': 0,
  'Distancia': 0},
 {'Origen': 'LA CARLOTA',
  'ID origen': 3,
  'Destino': 'OLAVARRIA',
  'ID destino': 1,
  'Carga': 16948,
  'Distancia': 0},
 {'Origen': 'VENADO TUERTO',
  'ID origen': 4,
  'Destino': 'OLAVARRIA',
  'ID destino': 1,
  'Carga': 275000,
  'Distancia': 0},
 {'Origen': 'OLAVARRIA',
  'ID origen': 1,
  'Destino': 'CABA',
  'ID destino': 2,
  'Carga': 133000,
  'Distancia': 500},
 {'Origen': 'CABA',
  'ID origen': 2,
  'Destino': 'CABA',
  'ID destino': 2,
  'Carga': 34000,
  'Distancia': 0},
 {'Origen': 'LA CARLOTA',
  'ID origen': 3,
  'Destino': 'CABA',
  'ID destino': 2,
  'Carga': 1325674,
  'Distancia': 750},
 {'Origen': 'VENADO TUERTO',
  'ID origen': 4,
  'Destino': 'CABA',
  'ID destino': 2,
  'Carga': 12000000,
  'Distancia': 200},
 {'Origen': 'OLAVARRIA',
  'ID origen': 1,
  'Destino': 'LA CARLOTA',
  'ID destino': 3,
  'Carga': 1300,
  'Distancia': 0},
 {'Origen': 'CABA',
  'ID origen': 2,
  'Destino': 'LA CARLOTA',
  'ID destino': 3,
  'Carga': 2200,
  'Distancia': 0},
 {'Origen': 'LA CARLOTA',
  'ID origen': 3,
  'Destino': 'LA CARLOTA',
  'ID destino': 3,
  'Carga': 4200000,
  'Distancia': 0},
 {'Origen': 'VENADO TUERTO',
  'ID origen': 4,
  'Destino': 'LA CARLOTA',
  'ID destino': 3,
  'Carga': 0,
  'Distancia': 0},
 {'Origen': 'OLAVARRIA',
  'ID origen': 1,
  'Destino': 'VENADO TUERTO',
  'ID destino': 4,
  'Carga': 50000,
  'Distancia': 0},
 {'Origen': 'CABA',
  'ID origen': 2,
  'Destino': 'VENADO TUERTO',
  'ID destino': 4,
  'Carga': 15000,
  'Distancia': 0},
 {'Origen': 'LA CARLOTA',
  'ID origen': 3,
  'Destino': 'VENADO TUERTO',
  'ID destino': 4,
  'Carga': 65000,
  'Distancia': 0},
 {'Origen': 'VENADO TUERTO',
  'ID origen': 4,
  'Destino': 'VENADO TUERTO',
  'ID destino': 4,
  'Carga': 10000,
  'Distancia': 0}]

lista_camion_granos = [{'Origen': 'OLAVARRIA',
  'ID origen': 1,
  'Destino': 'OLAVARRIA',
  'ID destino': 1,
  'Carga': 39319,
  'Distancia': 0},
 {'Origen': 'CABA',
  'ID origen': 2,
  'Destino': 'OLAVARRIA',
  'ID destino': 1,
  'Carga': 0,
  'Distancia': 0},
 {'Origen': 'LA CARLOTA',
  'ID origen': 3,
  'Destino': 'OLAVARRIA',
  'ID destino': 1,
  'Carga': 16948,
  'Distancia': 0},
 {'Origen': 'VENADO TUERTO',
  'ID origen': 4,
  'Destino': 'OLAVARRIA',
  'ID destino': 1,
  'Carga': 275000,
  'Distancia': 0},
 {'Origen': 'OLAVARRIA',
  'ID origen': 1,
  'Destino': 'CABA',
  'ID destino': 2,
  'Carga': 180000,
  'Distancia': 500},
 {'Origen': 'CABA',
  'ID origen': 2,
  'Destino': 'CABA',
  'ID destino': 2,
  'Carga': 85000,
  'Distancia': 0},
 {'Origen': 'LA CARLOTA',
  'ID origen': 3,
  'Destino': 'CABA',
  'ID destino': 2,
  'Carga': 50000,
  'Distancia': 750},
 {'Origen': 'VENADO TUERTO',
  'ID origen': 4,
  'Destino': 'CABA',
  'ID destino': 2,
  'Carga': 90000,
  'Distancia': 200},
 {'Origen': 'OLAVARRIA',
  'ID origen': 1,
  'Destino': 'LA CARLOTA',
  'ID destino': 3,
  'Carga': 1300,
  'Distancia': 0},
 {'Origen': 'CABA',
  'ID origen': 2,
  'Destino': 'LA CARLOTA',
  'ID destino': 3,
  'Carga': 2200,
  'Distancia': 0},
 {'Origen': 'LA CARLOTA',
  'ID origen': 3,
  'Destino': 'LA CARLOTA',
  'ID destino': 3,
  'Carga': 4200000,
  'Distancia': 0},
 {'Origen': 'VENADO TUERTO',
  'ID origen': 4,
  'Destino': 'LA CARLOTA',
  'ID destino': 3,
  'Carga': 0,
  'Distancia': 0},
 {'Origen': 'OLAVARRIA',
  'ID origen': 1,
  'Destino': 'VENADO TUERTO',
  'ID destino': 4,
  'Carga': 15000,
  'Distancia': 0},
 {'Origen': 'CABA',
  'ID origen': 2,
  'Destino': 'VENADO TUERTO',
  'ID destino': 4,
  'Carga': 20000,
  'Distancia': 0},
 {'Origen': 'LA CARLOTA',
  'ID origen': 3,
  'Destino': 'VENADO TUERTO',
  'ID destino': 4,
  'Carga': 150000,
  'Distancia': 0},
 {'Origen': 'VENADO TUERTO',
  'ID origen': 4,
  'Destino': 'VENADO TUERTO',
  'ID destino': 4,
  'Carga': 40000,
  'Distancia': 0}]